language: rust
rust:
  - 1.31.0
  - stable
  - nightly
cache: cargo
sudo: false
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
    - CARGO_INCREMENTAL=0  # decrease size of `target` to make the cache smaller
    - NO_STD_TARGET=thumbv7em-none-eabi
script:
  # Run tests on x86-64
  - cargo test --all
  # Make sure it builds on #![no_std]-only targets
  - rustup target add $NO_STD_TARGET
  - cargo build --target $NO_STD_TARGET
notifications:
  email:
    on_success: never
